steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions', 'deploy',
      'webhook-receiver',
      '--region', '${_REGION}',
      '--allow-unauthenticated',
      '--entry-point', 'receive',
      '--memory', '${_MEMORY}',
      '--runtime', '${_RUNTIME}',
      '--source', '${_SOURCE}',
      '--timeout', '${_TIMEOUT}',
      '--set-env-vars', '[SECRET_TOKEN=${_SECRET_TOKEN}]',
      '--trigger-http'
    ]
